### ISSUE TITLE
MVP 1: Auth

### ISSUE THREAD

**Issue by homelissa** [homelissa/hipcamp#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
  - [x] When errors are displayed, the input boxes should not move
- [x] Smooth, bug free navigation
  - [x] Login errors clears when switching from login form to sign up form (and vice-versa)
  - [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
  - [x] Errors should display for both `/signup` and`/login`.
  - [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Adequate and appropriate seeds
  - [x] Demo Login Works

**Comment by xnanodax** [comment]
Awesome! Great work! 

## Additional Comments
- [ ] Consider the following about the "x" in your signup/login modal: https://wesbos.com/times-html-entity-close-button/
- [ ] I suggest to add more padding around the modal component
- [ ] On hipcamp, when a modal "pops" up, the background overlay behind is white-ish rather than gray-ish
- [ ] On hipcamp, the the modal component has a slight shadow border.

**Comment by homelissa** [comment]
Hey Cynthia - made the changes! Can you take a look? Thanks!

**Comment by xnanodax** [comment]
Hey Melissa! Great work so far. All functionality is there. We still have styling. It should look much closer to HipCamp's Navbar.

- **HipCamp**
![screen shot 2018-06-14 at 8 04 41 am](https://user-images.githubusercontent.com/20424731/41420578-a3fa6d32-6fa9-11e8-9cf0-87a66562198e.png)

- **HippyCamp**
![screen shot 2018-06-14 at 8 05 25 am](https://user-images.githubusercontent.com/20424731/41420611-bd6e006c-6fa9-11e8-9072-68b254ec0281.png)


Also, watch up for the position of the font between the welcome message and the log out button: 
![screen shot 2018-06-14 at 8 01 36 am](https://user-images.githubusercontent.com/20424731/41420638-cde886b0-6fa9-11e8-8032-2d2cb9a36bd3.png)

**Comment by homelissa** [comment]
my Navbar only has the logo, the sign up, and log in functionality. What else did you want to see in this feature?

**Comment by xnanodax** [comment]
It is up to you what you want on your navbar. I'm saying the styilng (the font, spacing, size, position) needs to look similar to hip camp's.

**Comment by homelissa** [comment]
I've updated the font, spacing size and position so that the navbar looks more similar to hipcamp's. Can you please take another look?

**Comment by xnanodax** [comment]
Great improvements!

I still see the following misaligned welcome message with the log out button
![screen shot 2018-06-15 at 9 43 30 am](https://user-images.githubusercontent.com/20424731/41479611-9bb9c08c-7080-11e8-89f7-6b16d9d08567.png)

**Comment by homelissa** [comment]
They should be aligned now. 
![screen shot 2018-06-15 at 10 12 39 am](https://user-images.githubusercontent.com/35046910/41481198-f2bac8fe-7085-11e8-93a3-83bd5835abce.png)

**Comment by xnanodax** [comment]
Awesome!
