### ISSUE TITLE
MVP 2: Listing

### ISSUE THREAD

**Issue by homelissa** [homelissa/hipcamp#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Seeded with info to demonstrate this feature

**Comment by xnanodax** [comment]
## Additional Comments
- [ ] Seed the data with a minimum of 9~10 listings.
- [ ] Add a few more touches with styling and positioning.

**Comment by homelissa** [comment]
Hey Cynthia - made the changes mentioned above. Can you take another look? Thanks!

**Comment by xnanodax** [comment]
Great work! Your images on your seed file is amazing! 

This is a great start to your listings. I cant wait to see when you add more listing descriptions to display since you have already set up that in the backend.
