### ISSUE TITLE
MVP 4: Reviews

### ISSUE THREAD

**Issue by homelissa** [homelissa/hipcamp#6]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Seeded with info to demonstrate this feature

**Comment by xnanodax** [comment]
Great work on the reviews! I can add, update, and delete them.

## Functionality
- [ ] A user can add multiple reviews to the same camp site. Is this what you intended?

## Styling
- [ ] I see different font sizes between different reviews:
![screen shot 2018-06-14 at 8 13 44 am](https://user-images.githubusercontent.com/20424731/41421157-f3b1eb38-6faa-11e8-84ff-cdf8dcc0756d.png)

**Comment by homelissa** [comment]
I haven't added the validation to prevent a user from adding multiple reviews to the same listing. I didn't plan to include this in my MVP.

**Comment by homelissa** [comment]
The font sizes should be consistent among different reviews now. Can you take another look?

**Comment by xnanodax** [comment]
Great work!
